var dj = localStorage.getItem("dj");
console.log(dj);
var hd = localStorage.getItem("hd");
console.log(희두);
var gm = localStorage.getItem("gm");
console.log(규민);
var jy = localStorage.getItem("jy");
console.log(주원);
var dh = localStorage.getItem("dh");
console.log(다혜);
var ny = localStorage.getItem("ny");
console.log(나연);
var hy = localStorage.getItem("hy");
console.log(해은);
var sk = localStorage.getItem("sk");
console.log(서경);